name: Execute Playwright Automation Tests
on:
    workflow_call:
        inputs:
            cucumber-tag:
                required: true
                description: Add the cucumber tag of the tests you would like to run.
                type: string
            web-browser:
                required: false
                default: chromium
                description: The browser the test will run in
                type: string

jobs: 
    execute-automation-tests:
        name: Execute Playwright Automation Tests
        runs-on: ubuntu-22.04
        permissions: 
            actions: write
            contents: write
        steps:
        - uses: actions/checkout@v4

        - name: Set Up Node
          uses: ./.github/actions/setup-node
          with:
            working-directory: ./automation
        
        - name: Generate .ENV file
          working-directory: ./automation
          shell: bash
          run: |
            echo 'BROWSER=${{ inputs.web-browser }}' > .env
            echo 'WEBSITE_URL=${{ vars.WEBSITE_URL }}' >> .env

        - name: Install browsers
          working-directory: ./automation
          run: npx playwright install
          
        - name: Execute Tests
          working-directory: ./automation
          run: 
            npx cucumber-js --tags "${{ inputs.cucumber-tag }}"
         
        - name: Upload Video of Tests
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: videos-test
            path: automation/reporting/video/
        
        - name: Upload screenshots of failed tests
          if: failure()
          uses: actions/upload-artifact@v4
          with:
            name: failed-test-screenshots
            path: automation/reporting/screenshots/
         
        - name: Load test report history
          uses: actions/checkout@v3
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages

        - name: Build test report
          uses: simple-elf/allure-report-action@v1.7
          if: always()
          with:
            gh_pages: gh-pages
            allure_history: allure-history
            allure_results: automation/reporting/allure/allure-results

        - name: Publish test report
          uses: peaceiris/actions-gh-pages@v4
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history






