name: Trigger Playwright Automation Tests
on:
    schedule:
    # Run at 00:00 UTC every day
    - cron: "0 19 * * *"
    workflow_dispatch:
      inputs:
        cucumber-tags:
          description: 'Test scenario tags'
          required: true
          default: '@WebTableTests'
          type: string

jobs:
    execute-tests:
      name: Run Playwright Automation Tests
      permissions: 
        actions: write
        contents: write
      uses: ./.github/workflows/_run-automation-test-workflow.yml
      with:
        cucumber-tag: ${{ inputs.cucumber-tags || '@WebTableTests' }}